(() => {
  const URL = 'wss://api.dexscreener.com/token-profiles/latest/v1', TOKEN_URL = 'https://api.dexscreener.com/tokens/v1', MAX = 1000, SHOW = 100;
  const defaults = ['robinhood','sol','bsc','base','eth','arbitrum','arc','hyperevm','xlayer'];
  const supportedChains = new Set(defaults);
  const state = {events:[], selected:new Set(['robinhood','eth']), dexSelected:new Set(['gmgn']), read:new Set(JSON.parse(localStorage.getItem('dex-read')||'[]')), known:new Set(defaults), backoff:1000, audio:null, sound:true};
  const msg=(key,substitutions)=>globalThis.chrome?.i18n?.getMessage(key,substitutions)||key;
  const localize=()=>{if(document.documentElement)document.documentElement.lang=globalThis.chrome?.i18n?.getUILanguage?.()||'en';document.title=msg('extensionName');document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=msg(e.dataset.i18n));document.querySelectorAll('[data-i18n-title]').forEach(e=>e.title=msg(e.dataset.i18nTitle));document.querySelectorAll('[data-i18n-aria-label]').forEach(e=>e.setAttribute('aria-label',msg(e.dataset.i18nAriaLabel)))};
  const $ = s => document.querySelector(s), esc = v => String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c])), short=(v,n=5)=>v&&v.length>n*2+3?`${v.slice(0,n)}…${v.slice(-n)}`:(v||'—'), time=v=>{const d=new Date(v);return isNaN(d)?'--:--:--':d.toLocaleTimeString([],{hour12:false})};
  const normalizeChain=v=>({ethereum:'eth',solana:'sol'}[String(v).toLowerCase()]||String(v).toLowerCase());
  const chainName=v=>({robinhood:'Robinhood',sol:'SOL',bsc:'BSC',base:'BASE',eth:'ETH',arbitrum:'Arbitrum',arc:'ARC',hyperevm:'HyperEVM',xlayer:'X Layer'}[String(v).toLowerCase()]||String(v||'—').toUpperCase());
  const chainShort=v=>({robinhood:'RH',sol:'SOL',bsc:'BSC',base:'BASE',eth:'ETH',arbitrum:'ARB',arc:'ARC',hyperevm:'HYPEREVM',xlayer:'XLAYER'}[String(v).toLowerCase()]||String(v||'—').toUpperCase());
  const dexNames={debot:'DeBot',binance:'Binance',gmgn:'GMGN',okx:'OKX'};
  const dexLinks={gmgn:'https://gmgn.ai/',debot:'https://debot.ai/',binance:'https://www.binance.com/'};
  const dexIcons={gmgn:'gmgn.svg',debot:'debot.png',binance:'bn.png',okx:'OKX_logo.jpg'};
  const binanceChains=new Set(['robinhood','sol','bsc','base','eth']);
  const debotChains=new Set(['robinhood','sol','bsc','base','eth','arbitrum','arc','hyperevm']);
  const okxChains=new Set(['robinhood','sol','bsc','base','eth','arbitrum','xlayer']);
  const tokenSymbols=new Map();
  const dexChainName=chain=>chain==='sol'?'solana':chain;
  const apiChainName=chain=>({eth:'ethereum',sol:'solana'}[chain]||chain);
  const okxChainName=chain=>chain==='robinhood'?'robinhood-chain':dexChainName(chain);
  const dexUrl=(dex,e)=>{if(dex==='gmgn')return `https://gmgn.ai/${encodeURIComponent(e.chainId)}/token/GTWdnLSv_${encodeURIComponent(e.tokenAddress)}`;if(dex==='binance')return binanceChains.has(e.chainId)?`https://web3.binance.com/token/${encodeURIComponent(e.chainId)}/${encodeURIComponent(e.tokenAddress)}?ref=PZGZ6O5N`:null;if(dex==='debot')return debotChains.has(e.chainId)?`https://debot.ai/token/${encodeURIComponent(dexChainName(e.chainId))}/325634_${encodeURIComponent(e.tokenAddress)}`:null;if(dex==='okx')return okxChains.has(e.chainId)?`https://web3.okx.com/token/${encodeURIComponent(okxChainName(e.chainId))}/${encodeURIComponent(e.tokenAddress)}?ref=ALPHALIVE`:null;return dexLinks[dex]};
  const lookupSymbol=e=>{const key=`${e.chainId}:${e.tokenAddress}`;if(!tokenSymbols.has(key))tokenSymbols.set(key,(async()=>{try{const r=await fetch(`${TOKEN_URL}/${encodeURIComponent(apiChainName(e.chainId))}/${encodeURIComponent(e.tokenAddress)}`);if(!r.ok)return '';const pairs=await r.json(),address=String(e.tokenAddress);for(const pair of Array.isArray(pairs)?pairs:[]){for(const token of [pair.baseToken,pair.quoteToken]){if(token?.address===address||(e.chainId!=='sol'&&String(token?.address).toLowerCase()===address.toLowerCase()))return token.symbol||''}}return ''}catch{return ''}})());return tokenSymbols.get(key)};
  const name=e=>{const d=e.description||'',labeled=d.match(/([A-Z][A-Za-z0-9'’.-]*(?:\s+[A-Z][A-Za-z0-9'’.-]*){0,4})\s+\(([A-Z][A-Z0-9]{1,11})\)/);return String(e.tokenSymbol||e.symbol||e.name||e.raw?.symbol||e.raw?.name||labeled?.[1]||d.match(/\$[A-Za-z0-9_]{2,20}/)?.[0]||d.match(/\(([A-Z][A-Z0-9]{1,11})\)/)?.[1]||short(e.tokenAddress,6)).replace(/\$/g,'')};
  const items=data=>{const p=JSON.parse(data);return Array.isArray(p)?p:(Array.isArray(p.data)?p.data:[p])};
  const links=e=>{const out=[];for(const k of state.dexSelected){const u=dexUrl(k,e),icon=dexIcons[k];if(u&&icon)out.push(`<a class="dex-action ${k}" href="${esc(u)}" target="_blank" rel="noopener" title="${esc(msg('openDex',dexNames[k]))}"><img src="image/${icon}" alt="${esc(dexNames[k])}"></a>`)}const x=(e.links||[]).find(l=>/twitter|x/i.test(`${l.type} ${l.label}`));const w=(e.links||[]).find(l=>/website|web/i.test(`${l.type} ${l.label}`));if(x?.url)out.push(`<a class="icon-action x-action" href="${esc(x.url)}" target="_blank" rel="noopener" title="${esc(msg('openX'))}" aria-label="${esc(msg('openX'))}"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 4h4.6l3.3 4.7L16.8 4H19l-5.1 6.1L20 20h-4.6l-3.8-5.4L7.1 20H5l5.4-6.6L5 4Z" fill="currentColor"/></svg></a>`);if(w?.url)out.push(`<a class="icon-action web-action" href="${esc(w.url)}" target="_blank" rel="noopener" title="${esc(msg('openWebsite'))}" aria-label="${esc(msg('openWebsite'))}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><circle cx="12" cy="12" r="8.5"/><path d="M3.8 12h16.4M12 3.5c2.2 2.4 3.3 5.2 3.3 8.5S14.2 18.1 12 20.5C9.8 18.1 8.7 15.3 8.7 12S9.8 5.9 12 3.5Z"/></svg></a>`);out.push(`<button class="icon-action read-action" data-read="${esc(e.id)}" title="${esc(msg('markRead'))}" aria-label="${esc(msg('markRead'))}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 7h16M9 7V4h6v3m-9 0 1 13h10l1-13M10 11v6m4-6v6"/></svg></button>`);return out.join('')};
  function setStatus(ok){$('#live').className=`live ${ok?'':'reconnecting'}`;$('#live').innerHTML=`<i></i> ${msg(ok?'online':'reconnecting')}`;}
  function picker(){const chains=[...state.known].sort((a,b)=>a==='robinhood'?-1:b==='robinhood'?1:chainName(a).localeCompare(chainName(b)));const labels=[...state.selected].map(chainShort);$('#chain-summary').textContent=labels.length<=3?labels.join(' · ')||msg('noneSelected'):`${labels.slice(0,2).join(' · ')} +${labels.length-2}`;$('#chain-picker').innerHTML=chains.map(c=>`<label class="chain-check" title="${esc(chainName(c))}"><input type="checkbox" value="${esc(c)}" ${state.selected.has(c)?'checked':''}><span>${chainShort(c)}</span></label>`).join('')}
  function dexPicker(){const labels=[...state.dexSelected].map(k=>dexNames[k]);$('#dex-summary').textContent=labels.length?labels.join(' · '):msg('noneSelected');$('#dex-picker').innerHTML=Object.entries(dexNames).map(([k,label])=>`<label class="chain-check"><input type="checkbox" value="${k}" ${state.dexSelected.has(k)?'checked':''}><span>${label}</span></label>`).join('')}
  function render(){const unread=state.events.filter(e=>!state.read.has(e.id));picker();dexPicker();const rows=unread.filter(e=>state.selected.has(e.chainId)).slice(0,SHOW);if(!rows.length){$('#feed').innerHTML=`<div class="empty">${esc(msg('emptyTitle'))}<span>${esc(msg('emptySubtitle'))}</span></div>`;return}$('#feed').innerHTML=rows.map(e=>`<article class="event"><div class="token" title="${esc(e.tokenAddress)}"><img src="${esc(e.icon||'')}" onerror="this.style.visibility='hidden'"><div class="token-main"><div class="token-name">${esc(name(e))}</div><div class="token-sub"><span class="chain">${chainShort(e.chainId)}</span><span class="token-address" data-address="${esc(e.tokenAddress)}">${short(esc(e.tokenAddress))}</span></div></div></div><aside class="event-side"><time class="time">${time(e.receivedAt)}</time><div class="actions">${links(e)}</div></aside></article>`).join('')}
  const audio=()=>state.audio||(state.audio=new(window.AudioContext||window.webkitAudioContext)()),beep=()=>{if(!state.sound)return;try{const a=audio(),o=a.createOscillator(),g=a.createGain();o.frequency.value=740;g.gain.setValueAtTime(.035,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.12);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.12)}catch{}};
  function connect(){setStatus(false);const ws=new WebSocket(URL);state.socket=ws;ws.onopen=()=>{state.backoff=1000;setStatus(true)};ws.onmessage=m=>{let list;try{list=items(m.data)}catch{return}list.forEach(item=>{if(!item.chainId||!item.tokenAddress)return;const chainId=normalizeChain(item.chainId);if(!supportedChains.has(chainId))return;const e={...item,chainId,type:'PROFILE',receivedAt:new Date().toISOString()};e.id=[e.chainId,e.tokenAddress,e.url,e.icon,e.description].join('|');if(state.events.some(old=>old.id===e.id))return;state.events.unshift(e);state.events=state.events.slice(0,MAX);lookupSymbol(e).then(tokenSymbol=>{if(tokenSymbol){e.tokenSymbol=tokenSymbol;render()}});beep();render()})};ws.onerror=()=>ws.close();ws.onclose=()=>{if(state.socket!==ws)return;setStatus(false);clearTimeout(state.reconnectTimer);state.reconnectTimer=setTimeout(connect,state.backoff);state.backoff=Math.min(state.backoff*2,30000)}}
  function refresh(){clearTimeout(state.reconnectTimer);const old=state.socket;if(old){old.onmessage=null;old.onerror=null;old.onclose=null;old.close()}state.backoff=1000;connect()}
  $('#chain-picker').onchange=e=>{if(e.target.type!=='checkbox')return;e.target.checked?state.selected.add(e.target.value):state.selected.delete(e.target.value);render()};$('#dex-picker').onchange=e=>{if(e.target.type!=='checkbox')return;e.target.checked?state.dexSelected.add(e.target.value):state.dexSelected.delete(e.target.value);render()};$('#refresh').onclick=refresh;$('#sound').onclick=()=>{state.sound=!state.sound;$('#sound').classList.toggle('on',state.sound);$('#sound').classList.toggle('off',!state.sound);$('#sound').title=msg(state.sound?'soundOff':'soundOn');$('#sound').setAttribute('aria-label',$('#sound').title);if(state.sound)audio()?.resume()};document.addEventListener('click',e=>{if(!e.target.closest('details'))document.querySelectorAll('details[open]').forEach(d=>d.open=false);const r=e.target.closest('[data-read]');if(r){state.read.add(r.dataset.read);localStorage.setItem('dex-read',JSON.stringify([...state.read]));render();return}const n=e.target.closest('[data-address],[data-copy]');if(n)navigator.clipboard?.writeText(n.dataset.address||n.dataset.copy).then(()=>{const old=n.textContent;n.textContent=msg('copied');setTimeout(()=>n.textContent=old,1000)})});setInterval(()=>$('#clock').textContent=new Date().toLocaleTimeString([],{hour12:false}),1000);localize();render();connect();
})();
